config/routes.rb
Rails.application.routes.draw do

  resources :maintainers
  
  get 'administration/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  scope "auth" do 
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
    }
  end

  resources :users

  authenticated :user, lambda {|u| u.role == "admin"} do
    resources :communes
    resources :cities
    resources :products
    resources :sub_categories
    resources :categories
    get 'administration', to: "home#administration"
  end

  authenticated :user, lambda {|u| u.role == "client"} do
    root to: "market#products", as: "client_user"
  end

  #marketplace routes
  get 'market/products'
  get 'market/categories'
  get 'market/shopping_cart'
  delete 'market/remove_cart_product', to: "market#remove_cart_product"
  get 'market/add_cart_product'
  get 'market/checkout'
  get 'market/post_sale'
  get 'market/product_detail'

  # landingpage routes
  get 'index', to: "home#index" 
  get 'blog', to: "home#blog"
  get 'contact', to: "home#contact"

  # Defines the root path route ("/")
  root "home#index"

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :delivery_addresses

  validates :name, presence: true

end

app/controllers/communes_controller.rb
class CommunesController < ApplicationController
  before_action :set_commune, only: %i[ show edit update destroy ]

  # GET /communes or /communes.json
  def index
    @communes = Commune.all
  end

  # GET /communes/1 or /communes/1.json
  def show
  end

  # GET /communes/new
  def new
    @commune = Commune.new
  end

  # GET /communes/1/edit
  def edit
  end

  # POST /communes or /communes.json
  def create
    @commune = Commune.new(commune_params)

    respond_to do |format|
      if @commune.save
        format.html { redirect_to commune_url(@commune), notice: "Commune was successfully created." }
        format.json { render :show, status: :created, location: @commune }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communes/1 or /communes/1.json
  def update
    respond_to do |format|
      if @commune.update(commune_params)
        format.html { redirect_to commune_url(@commune), notice: "Commune was successfully updated." }
        format.json { render :show, status: :ok, location: @commune }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communes/1 or /communes/1.json
  def destroy
    @commune.destroy

    respond_to do |format|
      format.html { redirect_to communes_url, notice: "Commune was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commune
      @commune = Commune.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commune_params
      params.require(:commune).permit(:name, :city_id)
    end
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/views/communes/_commune.html.erb
<div id="<%= dom_id commune %>">
  <p>
    <strong>Name:</strong>
    <%= commune.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= commune.city_id %>
  </p>

</div>

app/views/communes/_form.html.erb
<%= form_with(model: commune) do |form| %>
  <% if commune.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(commune.errors.count, "error") %> prohibited this commune from being saved:</h2>

      <ul>
        <% commune.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.text_field :city_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/communes/edit.html.erb
<h1>Editing commune</h1>

<%= render "form", commune: @commune %>

<br>

<div>
  <%= link_to "Show this commune", @commune %> |
  <%= link_to "Back to communes", communes_path %>
</div>

app/views/communes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Communes</h1>

<div id="communes">
  <% @communes.each do |commune| %>
    <%= render commune %>
    <p>
      <%= link_to "Show this commune", commune %>
    </p>
  <% end %>
</div>

<%= link_to "New commune", new_commune_path %>

app/views/communes/new.html.erb
<h1>New commune</h1>

<%= render "form", commune: @commune %>

<br>

<div>
  <%= link_to "Back to communes", communes_path %>
</div>

app/views/communes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @commune %>

<div>
  <%= link_to "Edit this commune", edit_commune_path(@commune) %> |
  <%= link_to "Back to communes", communes_path %>

  <%= button_to "Destroy this commune", @commune, method: :delete %>
</div>