config/routes.rb
Rails.application.routes.draw do

  resources :maintainers
  
  get 'administration/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  scope "auth" do 
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
    }
  end

  resources :users

  authenticated :user, lambda {|u| u.role == "admin"} do
    resources :communes
    resources :cities
    resources :products
    resources :sub_categories
    resources :categories
    get 'administration', to: "home#administration"
  end

  authenticated :user, lambda {|u| u.role == "client"} do
    root to: "market#products", as: "client_user"
  end

  #marketplace routes
  get 'market/products'
  get 'market/categories'
  get 'market/shopping_cart'
  delete 'market/remove_cart_product', to: "market#remove_cart_product"
  get 'market/add_cart_product'
  get 'market/checkout'
  get 'market/post_sale'
  get 'market/product_detail'

  # landingpage routes
  get 'index', to: "home#index" 
  get 'blog', to: "home#blog"
  get 'contact', to: "home#contact"

  # Defines the root path route ("/")
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories

  validates :name, presence: true
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :delivery_addresses

  validates :name, presence: true

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :commune
  belongs_to :user

  validates :name, presence: true
  validates :street_name, presence: true
  validates :street_number, presence: true
  validates :postal_code, presence: true
  validates :commune_id, presence: true

end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :sub_category

  scope :categories, -> { joins(sub_category: :category).map(&:category).uniq }

  validates :name, presence: true
  validates :description, presence: true
  validates :stock, presence: true
  validates :price, presence: true


  def category
    sub_category.category
  end
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :communes
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validate :product_stock
  after_commit :less_stock

  private

  def product_stock
    errors.add(:base, "Cantidad excede stock del producto") if product.stock < quantity
  end

  def less_stock
    stock = product.stock - quantity
    product.update(stock: stock)
  end
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :products

  validates :name, presence: true

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :delivery_addresses

  has_many :shopping_carts
  has_many :products, through: :shopping_carts
  accepts_nested_attributes_for :delivery_addresses
  validates :password, confirmation: true, unless: Proc.new { |a| a.password.blank? }
  validates :name, presence: true
  validates :role, presence: true

  def admin?
    role == "admin"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'landingpage'

  def index
  end

  def blog
  end

  def contact
  end
end

app/controllers/market_controller.rb
class MarketController < ApplicationController
  def products
    @q = Product.order(:name).ransack(params[:q])
    @products = @q.result(distinct: true).includes(sub_category: :category)
    @selected_categories = @products.categories
    @categories = Category.all
    @sub_categories = @selected_categories.map { |category| category.sub_categories}.flatten
  end

  def categories
    @categories = Category.all
  end

  def product_detail
    id = params[:id]
    @product = Product.find(id)
    @shopping_cart = ShoppingCart.new

  end

  def shopping_cart
    @cart_products = current_user.shopping_carts
  end

  def remove_cart_product
    ShoppingCart.find(params[:id]).destroy
    redirect_to market_shopping_cart_path
  end

  def add_cart_product
    quantity = params[:quantity]
    product_id = params[:product_id]
    @shopping_cart = ShoppingCart.new(user: current_user, product_id: product_id, quantity: quantity)
    @shopping_cart.save
    redirect_to market_shopping_cart_path 
  end

  def checkout
  end

  def post_sale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maintainers_helper.rb
module MaintainersHelper
    def association_name(entity, association, id)
        association = association.to_s.delete_suffix("_id").to_sym
        entity.association(association).reflection.class_name.constantize.find(id).name
    end

    def association_collection(entity, association)
        association = association.to_s.delete_suffix("_id").to_sym
        entity.association(association).reflection.class_name.constantize.all
    end
        
end

app/helpers/market_helper.rb
module MarketHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/market/_filter.html.erb
<div class="col-md-3">
  <div class="section__filters">
    <%= search_form_for @q, url: market_products_path do |f| %>
      <p class="section__descripcion"><%= @products.count %> Resultados</p>
      <div class="section__tags">
        <% @selected_categories.each do |categories| %>
          <div class="section__tag"><%= categories.name %> <span class="fa fa-close"></span></div>
        <% end %>
      </div>
      <div class="section__filters__category">
        <h5 class="section__title">Categorias</h5>
        <%= f.collection_check_boxes(:sub_category_category_id_in, @categories, :id, :name) do |b| %>
          <ul>
            <%= b.check_box(style: "display:none;", onclick: "submit()") %>
            <%= b.check_box(style: "display:none;", value: :category) %>
            <%= b.label("data-value": :category) %>
          </ul>
        <% end %>
      </div>
      <div class="section__tags">
        <% @sub_categories.each do |sub_category| %>
          <div class="section__tag"><%= sub_category.name %> <span class="fa fa-close"></span></div>
        <% end %>
      </div>
      <div class="section__filters__category">
        <h5 class="section__title">Sub categorias</h5>
        <%= f.collection_check_boxes(:sub_category_id_in, @sub_categories, :id, :name) do |b| %>
          <ul>
            <%= b.check_box(style: "display:none;", onclick: "submit()") %>
            <%= b.label %>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/market/categories.html.erb
<section class="section--header">
  <div class="section__banner">
    <div class="section__bg">
      <div class="bg"></div>
    </div>
    <div class="section__grad"></div>
    <div class="section__wrap section__wrap--header">
      <div class="section__content">
        <div class="section__body">
          <h1 class="h2 section__title">Conoce todos nuestros productos</h1>
          <p class="section__description">Iaculis velit leo metus maecenas at aenean vivamus rutrum justo convallis
            aenean.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section--categories">
  <div class="section__wrap">
    <div class="section__header"></div>
    <div class="section__body">
      <div class="cols">
        <% @categories.each do |category| %>
          <div class="col-xs-6 col-md-4">
            <article class="article--category">
              <div class="article__bg">
                <div class="bg"><%=  category.name %></div>
              </div>
              <div class="article__content">
                <h4 class="article__title"><%= category.name %></h4>
                <p class="article__description">Descripción
                </p>
                <%= link_to 'ver mas', market_products_path(q: {sub_category_id_in: category.sub_categories.map(&:id)}), class: "btn btn--sm btn--secondary" %>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/market/checkout.html.erb
<h1>Market#checkout</h1>
<p>Find me in app/views/market/checkout.html.erb</p>

app/views/market/post_sale.html.erb
<h1>Market#post_sale</h1>
<p>Find me in app/views/market/post_sale.html.erb</p>

app/views/market/product_detail.html.erb
<div id="sections">
  <section class="section--header">
    <div class="section__banner">
      <div class="section__bg">
        <div class="bg"></div>
      </div>
      <div class="section__grad"></div>
      <div class="section__wrap section__wrap--category">
        <div class="section__content">
          <div class="section__body">
            <h1 class="h2 section__title">Detalles del producto</h1>
            <p class="section__description">
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section--panel">
    <div class="section__wrap">
      <div class="section__body">
        <div class="container row">
          <div class="col-6">
            <%= image_tag(@product.image) if @product.image.attached?%>
          </div>
          <div class="col">
            <div class="d-flex flex-column h-100">
              <h2><%= @product.name %></h2>
              <p class="fs-3">Descripción del producto:</p>
              <hr />
              <p class="fs-3"><%= @product.description %></p>
              <div class="row align-self-end mt-auto">
              <p class="fs-4">Precio: <%= @product.price %></p>
              <p class="fs-4 <%= 'bg-danger' if @product.stock %>">Stock: <%= @product.stock %></p>
              <hr />
              <% if @shopping_cart.errors.any? %>
              <p>
                <%= @shopping_cart.errors.full_messages %>
              </p>
              <%end%>
              <p class="fs-4">Cantidad:</p>
              <div class="d-flex flex-row">
                <button id="minus"><i class="fa fa-circle-minus"></i></button>
                <label id="cart_quantity" class="px-2 fs-4">1</label>
                <button id="plus"><i class="fa fa-circle-plus"></i></button>
              </div>
              <button value="1" id="add_to_cart" class="btn btn-success">Agregar al carrito de compras <i class="fa-solid fa-cart-plus"></i></button>
              </div>
            </div>
          </div>
          </div>
      </div>
    </div>
  </section>
</div>

<script>
$(function() {
  const stock = <%= @product.stock %>
  $("#minus").click(function() {
    let quantity = $("#add_to_cart").val();
    console.log(quantity);
    if(quantity > 0){
      quantity --;
      $("#add_to_cart").val(quantity)
      $("#cart_quantity").text(quantity);
    }

  })
  $("#plus").click(function() {
    let quantity = $("#add_to_cart").val();
    console.log(quantity);
    if(quantity >= 0 && quantity < stock){
      quantity ++;
      $("#add_to_cart").val(quantity)
      $("#cart_quantity").text(quantity);
    }

  });
  if(stock <= 0) $("#add_to_cart").attr("disabled", "disabled");

  $("#add_to_cart").click(function() {
    const quantity = $(this).val();
    const product_id = <%= @product.id %>
    $.get("/market/add_cart_product?quantity=" + quantity + "&product_id="+ product_id, function(data) {
      window.location.href = "/market/shopping_cart?id=" + product_id
    })
  })
})
</script>

app/views/market/products.html.erb
<div id="sections">
  <section class="section--header">
    <div class="section__banner">
      <div class="section__bg">
        <div class="bg"></div>
      </div>
      <div class="section__grad"></div>
      <div class="section__wrap section__wrap--category">
        <div class="section__content">
          <div class="section__body">
            <h1 class="h2 section__title">Los resultados de tu búsqueda</h1>
            <p class="section__description">
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section--panel">
    <div class="section__wrap">
      <div class="section__body">
        <div class="cols">
          <%= render 'filter' %>
          <div class="col-md-9">
            <div class="section__products">
              <div class="cols">
                <% @products.each do |product| %>
                  <div class="col-xs-6 col-md-4">
                    <article class="article--product">
                      <div class="article__img"> <%= image_tag(product.image) if product.image.attached? %></div>
                      <div class="article__body">
                        <h4 class="article__title"><%= product.name.upcase.capitalize %> </h4>
                        <%= link_to 'Ver más<span class="fa fa-angle-right"></span>'.html_safe, market_product_detail_path(id: product), class: "btn btn--sm" %>
                      </div>
                    </article>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/market/shopping_cart.html.erb
<div id="sections">
  <section class="section--header">
    <div class="section__banner">
      <div class="section__bg">
        <div class="bg"></div>
      </div>
      <div class="section__grad"></div>
      <div class="section__wrap section__wrap--category">
        <div class="section__content">
          <div class="section__body">
            <h1 class="h2 section__title">Carrito de Compras</h1>
            <p class="section__description">
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section--panel">
    <div class="section__wrap">
      <div class="section__body">
        <h1>Mis compras</h1>
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Descripción</th>
                            <th>Cantidad</th>
                            <th>Precio</th>
                            <th>Sub Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% total = 0%>
                        <% @cart_products.each do |cart_product| %>
                        <tr>
                            <td><%= cart_product.product.name %></td>
                            <td><%= cart_product.product.description %></td>
                            <td><i class="fa fa-circle-minus"></i><label class="px-2"> <%= cart_product.quantity %></label><i class="fa fa-circle-plus"></i></td>
                            <td><%= cart_product.product.price %></td>
                            <td><%= cart_product.quantity * cart_product.product.price %></td>
                            <td><%= link_to "<i class='fa-solid fa-trash-can'></i>".html_safe, market_remove_cart_product_path(id: cart_product.id), method: :delete %></td>
                        </tr>
                        <% total += cart_product.quantity * cart_product.product.price %>
                        <% end %>
                    </tbody> 
                </table>
                <table class="table">
                    <tbody>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Total : </td>
                            <td><%= total %></td>
                        </tr>
                    </tbody> 
                </table>
            </div>
        </div>
      </div>
    </div>
  </section>
</div>