config/routes.rb
Rails.application.routes.draw do

  resources :maintainers
  
  get 'administration/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  scope "auth" do 
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations'
    }
  end

  resources :users

  authenticated :user, lambda {|u| u.role == "admin"} do
    resources :communes
    resources :cities
    resources :products
    resources :sub_categories
    resources :categories
    get 'administration', to: "home#administration"
  end

  authenticated :user, lambda {|u| u.role == "client"} do
    root to: "market#products", as: "client_user"
  end

  #marketplace routes
  get 'market/products'
  get 'market/categories'
  get 'market/shopping_cart'
  delete 'market/remove_cart_product', to: "market#remove_cart_product"
  get 'market/add_cart_product'
  get 'market/checkout'
  get 'market/post_sale'
  get 'market/product_detail'

  # landingpage routes
  get 'index', to: "home#index" 
  get 'blog', to: "home#blog"
  get 'contact', to: "home#contact"

  # Defines the root path route ("/")
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories

  validates :name, presence: true
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :delivery_addresses

  validates :name, presence: true

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :commune
  belongs_to :user

  validates :name, presence: true
  validates :street_name, presence: true
  validates :street_number, presence: true
  validates :postal_code, presence: true
  validates :commune_id, presence: true

end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :sub_category

  scope :categories, -> { joins(sub_category: :category).map(&:category).uniq }

  validates :name, presence: true
  validates :description, presence: true
  validates :stock, presence: true
  validates :price, presence: true


  def category
    sub_category.category
  end
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :communes
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validate :product_stock
  after_commit :less_stock

  private

  def product_stock
    errors.add(:base, "Cantidad excede stock del producto") if product.stock < quantity
  end

  def less_stock
    stock = product.stock - quantity
    product.update(stock: stock)
  end
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :products

  validates :name, presence: true

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :delivery_addresses

  has_many :shopping_carts
  has_many :products, through: :shopping_carts
  accepts_nested_attributes_for :delivery_addresses
  validates :password, confirmation: true, unless: Proc.new { |a| a.password.blank? }
  validates :name, presence: true
  validates :role, presence: true

  def admin?
    role == "admin"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'landingpage'

  def index
  end

  def blog
  end

  def contact
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: %i[ show edit update destroy ]

  # GET /sub_categories or /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1 or /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories or /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully created." }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1 or /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to sub_category_url(@sub_category), notice: "Sub category was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1 or /sub_categories/1.json
  def destroy
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: "Sub category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maintainers_helper.rb
module MaintainersHelper
    def association_name(entity, association, id)
        association = association.to_s.delete_suffix("_id").to_sym
        entity.association(association).reflection.class_name.constantize.find(id).name
    end

    def association_collection(entity, association)
        association = association.to_s.delete_suffix("_id").to_sym
        entity.association(association).reflection.class_name.constantize.all
    end
        
end

app/helpers/market_helper.rb
module MarketHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category) do |form| %>
  <% if sub_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
        <% sub_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/_sub_category.html.erb
<div id="<%= dom_id sub_category %>">
  <p>
    <strong>Name:</strong>
    <%= sub_category.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= sub_category.category_id %>
  </p>

</div>

app/views/sub_categories/edit.html.erb
<h1>Editing sub category</h1>

<%= render "form", sub_category: @sub_category %>

<br>

<div>
  <%= link_to "Show this sub category", @sub_category %> |
  <%= link_to "Back to sub categories", sub_categories_path %>
</div>

app/views/sub_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sub categories</h1>

<div id="sub_categories">
  <% @sub_categories.each do |sub_category| %>
    <%= render sub_category %>
    <p>
      <%= link_to "Show this sub category", sub_category %>
    </p>
  <% end %>
</div>

<%= link_to "New sub category", new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New sub category</h1>

<%= render "form", sub_category: @sub_category %>

<br>

<div>
  <%= link_to "Back to sub categories", sub_categories_path %>
</div>

app/views/sub_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sub_category %>

<div>
  <%= link_to "Edit this sub category", edit_sub_category_path(@sub_category) %> |
  <%= link_to "Back to sub categories", sub_categories_path %>

  <%= button_to "Destroy this sub category", @sub_category, method: :delete %>
</div>